# -*- coding: utf-8 -*-
"""Visualizing YouTube Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iYHi5I-0iRk7JSgvHBMZ8kQGVCgD-thW
"""

#importing the YouTube Dataset

from google.colab import files
uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels.csv']))
display(df)

for col in ['subscribers', 'video views', 'video count']:
    df[col] = df[col].str.replace(',', '', regex=False)
    df[col] = pd.to_numeric(df[col])

display(df)

#Creating a Histogram
import plotly.express as px
fig = px.histogram(df, x='subscribers', title='Subscription Count')
fig.show()

#Creating a Pie Chart

import plotly.express as px
fig = px.pie(df, values='subscribers', names='category', title='YouTube Categories')
fig.show()

#Creating a boxplot
import plotly.express as px
fig = px.box(df, y='started', title='Years Started')
fig.show()